title: "Stef Pletinck"
logo: "assets/epse.png"
description: "Personal website and blog of developer Stef Pletinck"
author: Stef Pletinck
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-gist
